import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-black scrollbar scrollbar-thumb-gray-700 scrollbar-track-gray-600 ">
        {children}
      </body>
    </html>
  );
}
